/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevokedRouteImport } from './routes/revoked'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ManageUsersRouteImport } from './routes/manage-users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevRouteImport } from './routes/dev'
import { Route as BannedRouteImport } from './routes/banned'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsPreferencesRouteImport } from './routes/settings/preferences'
import { Route as SettingsGeneralRouteImport } from './routes/settings/general'
import { Route as SettingsAuditRouteImport } from './routes/settings/audit'
import { Route as CaseIdRouteImport } from './routes/case.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiGenerateAvatarRouteImport } from './routes/api/generate-avatar'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevokedRoute = RevokedRouteImport.update({
  id: '/revoked',
  path: '/revoked',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const BannedRoute = BannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SettingsRoute,
} as any)
const CaseIdRoute = CaseIdRouteImport.update({
  id: '/case/$id',
  path: '/case/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAvatarRoute = ApiGenerateAvatarRouteImport.update({
  id: '/api/generate-avatar',
  path: '/api/generate-avatar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/apps': typeof AppsRoute
  '/banned': typeof BannedRoute
  '/dev': typeof DevRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoked': typeof RevokedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/violations': typeof ViolationsRoute
  '/welcome': typeof WelcomeRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/case/$id': typeof CaseIdRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/apps': typeof AppsRoute
  '/banned': typeof BannedRoute
  '/dev': typeof DevRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoked': typeof RevokedRoute
  '/setup': typeof SetupRoute
  '/violations': typeof ViolationsRoute
  '/welcome': typeof WelcomeRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/case/$id': typeof CaseIdRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/apps': typeof AppsRoute
  '/banned': typeof BannedRoute
  '/dev': typeof DevRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revoked': typeof RevokedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/setup': typeof SetupRoute
  '/violations': typeof ViolationsRoute
  '/welcome': typeof WelcomeRoute
  '/api/generate-avatar': typeof ApiGenerateAvatarRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/case/$id': typeof CaseIdRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/apps'
    | '/banned'
    | '/dev'
    | '/forgot-password'
    | '/login'
    | '/manage-users'
    | '/reset-password'
    | '/revoked'
    | '/settings'
    | '/setup'
    | '/violations'
    | '/welcome'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/case/$id'
    | '/settings/audit'
    | '/settings/general'
    | '/settings/preferences'
    | '/settings/security'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/apps'
    | '/banned'
    | '/dev'
    | '/forgot-password'
    | '/login'
    | '/manage-users'
    | '/reset-password'
    | '/revoked'
    | '/setup'
    | '/violations'
    | '/welcome'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/case/$id'
    | '/settings/audit'
    | '/settings/general'
    | '/settings/preferences'
    | '/settings/security'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/apps'
    | '/banned'
    | '/dev'
    | '/forgot-password'
    | '/login'
    | '/manage-users'
    | '/reset-password'
    | '/revoked'
    | '/settings'
    | '/setup'
    | '/violations'
    | '/welcome'
    | '/api/generate-avatar'
    | '/auth/callback'
    | '/case/$id'
    | '/settings/audit'
    | '/settings/general'
    | '/settings/preferences'
    | '/settings/security'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  AppsRoute: typeof AppsRoute
  BannedRoute: typeof BannedRoute
  DevRoute: typeof DevRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ManageUsersRoute: typeof ManageUsersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevokedRoute: typeof RevokedRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SetupRoute: typeof SetupRoute
  ViolationsRoute: typeof ViolationsRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiGenerateAvatarRoute: typeof ApiGenerateAvatarRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CaseIdRoute: typeof CaseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revoked': {
      id: '/revoked'
      path: '/revoked'
      fullPath: '/revoked'
      preLoaderRoute: typeof RevokedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-users': {
      id: '/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banned': {
      id: '/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof BannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/case/$id': {
      id: '/case/$id'
      path: '/case/$id'
      fullPath: '/case/$id'
      preLoaderRoute: typeof CaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-avatar': {
      id: '/api/generate-avatar'
      path: '/api/generate-avatar'
      fullPath: '/api/generate-avatar'
      preLoaderRoute: typeof ApiGenerateAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  AppsRoute: AppsRoute,
  BannedRoute: BannedRoute,
  DevRoute: DevRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ManageUsersRoute: ManageUsersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevokedRoute: RevokedRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SetupRoute: SetupRoute,
  ViolationsRoute: ViolationsRoute,
  WelcomeRoute: WelcomeRoute,
  ApiGenerateAvatarRoute: ApiGenerateAvatarRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CaseIdRoute: CaseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
